// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_vtg7rlHVqXHxf_dHj66tYjdbTTA1KY',
    appId: '1:475925711098:web:526768b1902ac0c9ad6143',
    messagingSenderId: '475925711098',
    projectId: 'travel-app-lazy',
    authDomain: 'travel-app-lazy.firebaseapp.com',
    storageBucket: 'travel-app-lazy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRkFlSnQWg34TYFzB2xDVdlfQI4hpwgw',
    appId: '1:475925711098:android:91432ed70c7d3d30ad6143',
    messagingSenderId: '475925711098',
    projectId: 'travel-app-lazy',
    storageBucket: 'travel-app-lazy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtr_oNJW_7LUQkRBB0VLcyeUD9kfaIreE',
    appId: '1:475925711098:ios:724b19f60753bbb2ad6143',
    messagingSenderId: '475925711098',
    projectId: 'travel-app-lazy',
    storageBucket: 'travel-app-lazy.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtr_oNJW_7LUQkRBB0VLcyeUD9kfaIreE',
    appId: '1:475925711098:ios:724b19f60753bbb2ad6143',
    messagingSenderId: '475925711098',
    projectId: 'travel-app-lazy',
    storageBucket: 'travel-app-lazy.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx_vtg7rlHVqXHxf_dHj66tYjdbTTA1KY',
    appId: '1:475925711098:web:46c8f60429fa0287ad6143',
    messagingSenderId: '475925711098',
    projectId: 'travel-app-lazy',
    authDomain: 'travel-app-lazy.firebaseapp.com',
    storageBucket: 'travel-app-lazy.firebasestorage.app',
  );

}