import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> savePlacesToFirebase() async {
  final CollectionReference<Map<String, dynamic>> reference = FirebaseFirestore
      .instance
      .collection('CollectionOfPlaces');

  for (final Place place in places) {
    final String id =
        DateTime.now().toIso8601String() + Random().nextInt(1000).toString();
    // reference.doc('das');
    await reference.doc(id).set(place.convertToMap());
  }
}

String randomDate2025() {
  final Random rnd = Random();
  final int month = rnd.nextInt(12) + 1;
  final int day = rnd.nextInt(28) + 1;
  return '2025-${month.toString().padLeft(2, '0')}-${day.toString().padLeft(2, '0')}';
}

class Place {
  final String title;
  bool isActive;
  final String image;
  final double rating;
  final String date;
  final int price;
  final String address;
  final String vendor;
  final String vendorProfession;
  final String vendorProfile;
  final int review;
  final String bedAndBathroom;
  final double latitude;
  final double longitude;
  final List<String> imageUrls;

  Place({
    required this.title,
    this.isActive = true,
    required this.image,
    required this.rating,
    required this.date,
    required this.price,
    required this.address,
    required this.vendor,
    required this.vendorProfession,
    required this.vendorProfile,
    required this.review,
    required this.bedAndBathroom,
    required this.latitude,
    required this.longitude,
    required this.imageUrls,
  });

  Map<String, dynamic> convertToMap() {
    return <String, dynamic>{
      'title': title,
      'isActive': isActive,
      'image': image,
      'rating': rating,
      'date': date,
      'price': price,
      'address': address,
      'vendor': vendor,
      'vendorProfession': vendorProfession,
      'vendorProfile': vendorProfile,
      'review': review,
      'bedAndBathroom': bedAndBathroom,
      'latitude': latitude,
      'longitude': longitude,
      'imageUrls': imageUrls,
    };
  }
}

List<Place> places = <Place>[
  Place(
    title: 'Seaside Serenity Resort',
    isActive: false,
    image: 'https://picsum.photos/id/1018/400/300',
    rating: 4.9,
    date: randomDate2025(),
    price: 320,
    address: '12 Ocean View Dr, Malibu, CA 90265',
    vendor: 'Olivia Waters',
    vendorProfession: 'Resort Owner',
    vendorProfile: 'https://randomuser.me/api/portraits/women/45.jpg',
    review: 150,
    bedAndBathroom: '2 beds, 2 bathrooms',
    latitude: 34.0259,
    longitude: -118.7798,
    imageUrls: [
      'https://picsum.photos/id/1025/400/300',
      'https://picsum.photos/id/1024/400/300',
      'https://picsum.photos/id/1019/400/300',
    ],
  ),
  Place(
    title: 'Alpine Mountain Lodge',
    isActive: true,
    image: 'https://picsum.photos/id/103/400/300',
    rating: 4.7,
    date: randomDate2025(),
    price: 220,
    address: '77 Pine Ridge Rd, Aspen, CO 81611',
    vendor: 'Ethan Frost',
    vendorProfession: 'Mountain Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/32.jpg',
    review: 89,
    bedAndBathroom: '3 beds, 1 bathroom',
    latitude: 39.1911,
    longitude: -106.8175,
    imageUrls: [
      'https://picsum.photos/id/104/400/300',
      'https://picsum.photos/id/105/400/300',
      'https://picsum.photos/id/106/400/300',
    ],
  ),
  Place(
    title: 'Urban Boutique Hotel',
    isActive: false,
    image: 'https://picsum.photos/id/107/400/300',
    rating: 4.5,
    date: randomDate2025(),
    price: 180,
    address: '250 City Center Blvd, Chicago, IL 60601',
    vendor: 'Maya Brooks',
    vendorProfession: 'Hotel Manager',
    vendorProfile: 'https://randomuser.me/api/portraits/women/22.jpg',
    review: 120,
    bedAndBathroom: '1 bed, 1 bathroom',
    latitude: 41.8837,
    longitude: -87.6289,
    imageUrls: [
      'https://picsum.photos/id/108/400/300',
      'https://picsum.photos/id/109/400/300',
      'https://picsum.photos/id/110/400/300',
    ],
  ),
  Place(
    title: 'Tropical Rainforest Eco‑Lodge',
    isActive: true,
    image: 'https://picsum.photos/id/111/400/300',
    rating: 4.8,
    date: randomDate2025(),
    price: 150,
    address: 'Rainforest Way, Costa Rica',
    vendor: 'Luis Hernandez',
    vendorProfession: 'Eco Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/47.jpg',
    review: 98,
    bedAndBathroom: '2 beds, 1 bathroom',
    latitude: 9.7489,
    longitude: -83.7534,
    imageUrls: [
      'https://picsum.photos/id/112/400/300',
      'https://picsum.photos/id/113/400/300',
      'https://picsum.photos/id/114/400/300',
    ],
  ),
  Place(
    title: 'Historic Castle Stay',
    isActive: false,
    image: 'https://picsum.photos/id/115/400/300',
    rating: 4.9,
    date: randomDate2025(),
    price: 500,
    address: 'Old Castle Rd, Edinburgh, UK',
    vendor: 'Fiona MacLeod',
    vendorProfession: 'Castle Owner',
    vendorProfile: 'https://randomuser.me/api/portraits/women/59.jpg',
    review: 200,
    bedAndBathroom: '4 beds, 3 bathrooms',
    latitude: 55.9486,
    longitude: -3.1999,
    imageUrls: [
      'https://picsum.photos/id/116/400/300',
      'https://picsum.photos/id/117/400/300',
      'https://picsum.photos/id/118/400/300',
    ],
  ),
  Place(
    title: 'Desert Oasis Camp',
    isActive: true,
    image: 'https://picsum.photos/id/119/400/300',
    rating: 4.6,
    date: randomDate2025(),
    price: 140,
    address: 'Sahara Desert, Merzouga, Morocco',
    vendor: 'Rachid Nouiri',
    vendorProfession: 'Camp Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/65.jpg',
    review: 76,
    bedAndBathroom: '1 bed (tent), shared bathroom',
    latitude: 31.1086,
    longitude: -4.0110,
    imageUrls: [
      'https://picsum.photos/id/120/400/300',
      'https://picsum.photos/id/121/400/300',
      'https://picsum.photos/id/122/400/300',
    ],
  ),
  Place(
    title: 'Lakeside Wooden Cabin',
    isActive: false,
    image: 'https://picsum.photos/id/123/400/300',
    rating: 4.7,
    date: randomDate2025(),
    price: 200,
    address: 'Lakeview Drive, Lake Tahoe, CA',
    vendor: 'Grace Miller',
    vendorProfession: 'Cabin Host',
    vendorProfile: 'https://randomuser.me/api/portraits/women/11.jpg',
    review: 110,
    bedAndBathroom: '2 beds, 1 bathroom',
    latitude: 39.0968,
    longitude: -120.0324,
    imageUrls: [
      'https://picsum.photos/id/124/400/300',
      'https://picsum.photos/id/125/400/300',
      'https://picsum.photos/id/126/400/300',
    ],
  ),
  Place(
    title: 'Skyline Rooftop Hotel',
    isActive: true,
    image: 'https://picsum.photos/id/127/400/300',
    rating: 4.4,
    date: randomDate2025(),
    price: 210,
    address: '500 Rooftop St, New York, NY',
    vendor: 'James Parker',
    vendorProfession: 'Hotelier',
    vendorProfile: 'https://randomuser.me/api/portraits/men/25.jpg',
    review: 95,
    bedAndBathroom: '1 bed, 1 bathroom',
    latitude: 40.7128,
    longitude: -74.0060,
    imageUrls: [
      'https://picsum.photos/id/128/400/300',
      'https://picsum.photos/id/129/400/300',
      'https://picsum.photos/id/130/400/300',
    ],
  ),
  Place(
    title: 'Forest Treehouse Retreat',
    isActive: false,
    image: 'https://picsum.photos/id/131/400/300',
    rating: 4.8,
    date: randomDate2025(),
    price: 260,
    address: 'Whispering Pines, Oregon, USA',
    vendor: 'Sophie Green',
    vendorProfession: 'Nature Guide',
    vendorProfile: 'https://randomuser.me/api/portraits/women/76.jpg',
    review: 130,
    bedAndBathroom: '1 bed, 1 bathroom',
    latitude: 44.0582,
    longitude: -121.3153,
    imageUrls: [
      'https://picsum.photos/id/132/400/300',
      'https://picsum.photos/id/133/400/300',
      'https://picsum.photos/id/134/400/300',
    ],
  ),
  Place(
    title: 'Modern Minimalist Apartment',
    isActive: true,
    image: 'https://picsum.photos/id/135/400/300',
    rating: 4.3,
    date: randomDate2025(),
    price: 130,
    address: 'Downtown, Berlin, Germany',
    vendor: 'Lukas Schmidt',
    vendorProfession: 'Airbnb Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/52.jpg',
    review: 80,
    bedAndBathroom: '1 bed, 1 bathroom',
    latitude: 52.5200,
    longitude: 13.4050,
    imageUrls: [
      'https://picsum.photos/id/136/400/300',
      'https://picsum.photos/id/137/400/300',
      'https://picsum.photos/id/138/400/300',
    ],
  ),
  // 10 more places with similar pattern, using different Picsum IDs and vendors
  Place(
    title: 'Cliffside Luxury Villa',
    isActive: false,
    image: 'https://picsum.photos/id/139/400/300',
    rating: 5.0,
    date: randomDate2025(),
    price: 600,
    address: 'Santorini, Greece',
    vendor: 'Nikos Papadopoulos',
    vendorProfession: 'Villa Owner',
    vendorProfile: 'https://randomuser.me/api/portraits/men/83.jpg',
    review: 220,
    bedAndBathroom: '3 beds, 2 bathrooms',
    latitude: 36.3932,
    longitude: 25.4615,
    imageUrls: [
      'https://picsum.photos/id/140/400/300',
      'https://picsum.photos/id/141/400/300',
      'https://picsum.photos/id/142/400/300',
    ],
  ),
  Place(
    title: 'Beachfront Bungalow',
    isActive: true,
    image: 'https://picsum.photos/id/143/400/300',
    rating: 4.6,
    date: randomDate2025(),
    price: 280,
    address: 'Koh Samui, Thailand',
    vendor: 'Somsak Chai',
    vendorProfession: 'Resort Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/75.jpg',
    review: 105,
    bedAndBathroom: '2 beds, 1 bathroom',
    latitude: 9.5120,
    longitude: 100.0135,
    imageUrls: [
      'https://picsum.photos/id/144/400/300',
      'https://picsum.photos/id/145/400/300',
      'https://picsum.photos/id/146/400/300',
    ],
  ),
  Place(
    title: 'Countryside Cottage',
    isActive: false,
    image: 'https://picsum.photos/id/147/400/300',
    rating: 4.5,
    date: randomDate2025(),
    price: 160,
    address: 'Cotswolds, UK',
    vendor: 'William Clarke',
    vendorProfession: 'Cottage Owner',
    vendorProfile: 'https://randomuser.me/api/portraits/men/38.jpg',
    review: 90,
    bedAndBathroom: '2 beds, 1 bathroom',
    latitude: 51.8910,
    longitude: -1.6554,
    imageUrls: [
      'https://picsum.photos/id/148/400/300',
      'https://picsum.photos/id/149/400/300',
      'https://picsum.photos/id/150/400/300',
    ],
  ),
  Place(
    title: 'Rainforest Treehouse',
    isActive: true,
    image: 'https://picsum.photos/id/151/400/300',
    rating: 4.8,
    date: randomDate2025(),
    price: 270,
    address: 'Amazon, Brazil',
    vendor: 'Ana Silva',
    vendorProfession: 'Eco Host',
    vendorProfile: 'https://randomuser.me/api/portraits/women/60.jpg',
    review: 130,
    bedAndBathroom: '1 bed, 1 bathroom',
    latitude: -3.4653,
    longitude: -62.2159,
    imageUrls: [
      'https://picsum.photos/id/152/400/300',
      'https://picsum.photos/id/153/400/300',
      'https://picsum.photos/id/154/400/300',
    ],
  ),
  Place(
    title: 'Mountain Chalet Retreat',
    isActive: false,
    image: 'https://picsum.photos/id/155/400/300',
    rating: 4.7,
    date: randomDate2025(),
    price: 230,
    address: 'Swiss Alps, Switzerland',
    vendor: 'Hans Meier',
    vendorProfession: 'Chalet Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/20.jpg',
    review: 115,
    bedAndBathroom: '3 beds, 2 bathrooms',
    latitude: 46.8182,
    longitude: 8.2275,
    imageUrls: [
      'https://picsum.photos/id/156/400/300',
      'https://picsum.photos/id/157/400/300',
      'https://picsum.photos/id/158/400/300',
    ],
  ),
  Place(
    title: 'Luxury Penthouse Suite',
    isActive: true,
    image: 'https://picsum.photos/id/159/400/300',
    rating: 5.0,
    date: randomDate2025(),
    price: 700,
    address: 'Downtown Tokyo, Japan',
    vendor: 'Akira Yamamoto',
    vendorProfession: 'Hotel Owner',
    vendorProfile: 'https://randomuser.me/api/portraits/men/99.jpg',
    review: 250,
    bedAndBathroom: '2 beds, 2 bathrooms',
    latitude: 35.6895,
    longitude: 139.6917,
    imageUrls: [
      'https://picsum.photos/id/160/400/300',
      'https://picsum.photos/id/161/400/300',
      'https://picsum.photos/id/162/400/300',
    ],
  ),
  Place(
    title: 'Cozy Winter Cabin',
    isActive: false,
    image: 'https://picsum.photos/id/163/400/300',
    rating: 4.6,
    date: randomDate2025(),
    price: 180,
    address: 'Rocky Mountains, USA',
    vendor: 'Jack Turner',
    vendorProfession: 'Cabin Host',
    vendorProfile: 'https://randomuser.me/api/portraits/men/12.jpg',
    review: 85,
    bedAndBathroom: '2 beds, 1 bathroom',
    latitude: 39.1130,
    longitude: -106.5350,
    imageUrls: [
      'https://picsum.photos/id/164/400/300',
      'https://picsum.photos/id/165/400/300',
      'https://picsum.photos/id/166/400/300',
    ],
  ),
  Place(
    title: 'Mediterranean Seaview Apartment',
    isActive: true,
    image: 'https://picsum.photos/id/167/400/300',
    rating: 4.7,
    date: randomDate2025(),
    price: 240,
    address: 'Nice, France',
    vendor: 'Isabelle Martin',
    vendorProfession: 'Apartment Host',
    vendorProfile: 'https://randomuser.me/api/portraits/women/77.jpg',
    review: 120,
    bedAndBathroom: '2 beds, 1 bathroom',
    latitude: 43.7102,
    longitude: 7.2620,
    imageUrls: [
      'https://picsum.photos/id/168/400/300',
      'https://picsum.photos/id/169/400/300',
      'https://picsum.photos/id/170/400/300',
    ],
  ),
];
